# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94ddee2fec5d3d97136f8111aaba16c5cf0372f0921b3513192fbc2a98eeeb959c7c4ae00943697056eb8357e34083f2626d1689e296f5249c4a9fbfd53b3b9f

test:
  secret_key_base: e3e61e9019954dbbb6866d5060d250ab34a9fe07728129c8075cc6809f16097cc5f7ed97b36d28aa42d770679f992fa190185f4a5f2c3fd1cd8b811639d4d325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
